# https://github.com/lalcebo/json-schema/blob/master/serverless/reference.json
service: nest-non-api
frameworkVersion: "3"
useDotenv: true
plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-dotenv-plugin
  - serverless-deployment-bucket

custom:
  prune:
    automatic: true
    number: 3

  webpack:
    webpackConfig: "webpack.config.js" # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    keepOutputDirectory: true
    packager: "npm" # Packager that will be used to package your external modules
    excludeFiles: src/**/*.spec.ts # Provide a glob for files to ignore

  config:
    stage: ${opt:stage, 'development'}
    region: ${opt:region, 'us-east-1'}
    name: nest-non-api

provider:
  name: aws
  stage: ${self:custom.config.stage}
  runtime: nodejs18.x
  region: us-east-1
  deploymentBucket:
    name: ${self:service}
  deploymentPrefix: backend

  # Optional CloudFormation tags to apply to APIs and functions
  tags:
    appName: ${self:custom.config.name}

  # Optional CloudFormation tags to apply to the stack
  stackTags:
    appName: ${self:custom.config.name}

  httpApi:
    # https://www.serverless.com/framework/docs/providers/aws/events/http-api
    shouldStartNameWithService: true
    cors:
      allowedOrigins: "*"
      allowedHeaders: "*"
      allowedMethods: "*"
      allowCredentials: false

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_ENV: ${self:custom.config.stage}

functions:
  main:
    name: ${self:service}-function-${self:custom.config.stage}
    handler: dist/serverless.handler
    timeout: 15
    events:
      - httpApi: "*"
      - sqs:
          arn: arn:aws:sqs:us-east-1:927440925921:test-lambda-messaging.fifo
      # - sns:
      #     arn: arn:aws:sns:us-east-1:927440925921:mySampleTopic
      # - sns:
      #     arn: arn:aws:sns:us-east-1:927440925921:mySecondSampleTopic.fifo
      
      # https://github.com/mnapoli/externals/blob/master/serverless.yml
      # - eventBridge:
      #     eventBus: custom-saas-events
      #     pattern:
      #       source:
      #         - saas.external
      #     deadLetterQueueArn:
      #       Fn::GetAtt:
      #         - test-lambda-messaging.fifo
      #         - Arn
      #     retryPolicy:
      #       maximumEventAge: 3600
      #       maximumRetryAttempts: 3

      # - eventBridge: arn:aws:scheduler:us-east-1:927440925921:schedule/default/test-scheduling